// CoronaAction
const IMAGES_DATA_INIT = 'IMAGES_DATA_INIT';
const IMAGES_DATA_SUCCESS = 'IMAGES_DATA_SUCCESS';
const IMAGES_DATA_ERROR = 'IMAGES_DATA_ERROR';

export { IMAGES_DATA_INIT, IMAGES_DATA_SUCCESS, IMAGES_DATA_ERROR };
